# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: INSTANCE-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientTools
from opensilexClientTools.models.position_no_sql_get_dto import PositionNoSqlGetDto  # noqa: E501
from opensilexClientTools.rest import ApiException


class TestPositionNoSqlGetDto(unittest.TestCase):
    """PositionNoSqlGetDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPositionNoSqlGetDto(self):
        """Test PositionNoSqlGetDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientTools.models.position_no_sql_get_dto.PositionNoSqlGetDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
