# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: INSTANCE-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opensilexClientTools
from opensilexClientTools.models.entity_get_dto import EntityGetDTO  # noqa: E501
from opensilexClientTools.rest import ApiException


class TestEntityGetDTO(unittest.TestCase):
    """EntityGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityGetDTO(self):
        """Test EntityGetDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilexClientTools.models.entity_get_dto.EntityGetDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
