[tool.poetry]
name = "opensilexClientPython"
version = "0.1.0"
description = "Python package for importing and managing variables in OpenSILEX"
authors = ["JEMAA Nouha <nouha.jemaa@inrae.fr>"]
readme = "README.md"
packages = [
    { include = "opensilexClientPython", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.3.3"
pyyaml = "^6.0.3"
rich = "^14.2.0"
opensilexClientToolsPython = { git = "https://github.com/OpenSILEX/opensilexClientToolsPython.git", tag = "1.4.9" }
opensilex-py-client = { git = "ssh://git@forge.inrae.fr/OpenSILEX/data-analysis-visualisation/opensilex-clients/opensilex-ws-python-client.git", branch = "new_client_package" }

[tool.poetry.group.dev.dependencies]
pdoc = "*"
tomli = "*"
jupyter = "*"
notebook = "*"
nbconvert = "*"
ipykernel = "*"
matplotlib = "*"
jupytext = "*"
pytest = "*"
pytest-cov = "*"

[tool.poetry.scripts]
gen-doc = "pyscaf.documentation.scripts.parse_doc:gen_doc"
serve-doc = "pyscaf.documentation.scripts.parse_doc:serve_doc"
py-to-nb = "pyscaf.jupyter-tools.scripts.py_to_notebook:main"
exec-nb = "pyscaf.jupyter-tools.scripts.execute_notebook:main"
nb-to-html = "pyscaf.jupyter-tools.scripts.notebook_to_html:main"
py-to-nb-all = "pyscaf.jupyter-tools.scripts.main:py_to_nb_all"
exec-nb-all = "pyscaf.jupyter-tools.scripts.main:exec_nb_all"
nb-to-html-all = "pyscaf.jupyter-tools.scripts.main:nb_to_html_all"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyscaf.documentation]
output_path = "docs"

[tool.pyscaf.jupyter-tools]
python_notebook_dir = "notebooks/python"
jupyter_notebook_dir = "notebooks/ipynb"
pdf_dir = "generated/pdfs"
html_dir = "generated/html"
hide_input = false
hide_output = false
template_name = "classic"
template_path = ""
template_file = ""

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = ["-v", "--tb=short", "--strict-markers", "--strict-config", "--color=yes"]
markers = [
    "slow: marks tests as slow",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests"
]

[tool.ruff]
src = ["src"]
select = ["B", "C4", "E", "F", "N", "W", "I", "UP"]
line-length = 120
